### ISSUE TITLE
[Bug] Socket通信异常

### ISSUE THREAD

**Issue by Zhou-Shilin** [Twiyin0/koishi-plugin-minecraft-sync-msg#2]
见图。
![869F1CD5-B298-43F0-B69C-483BE3CC587D](https://github.com/Twiyin0/koishi-plugin-minecraft-sync-msg/assets/86581525/725610df-71cc-42ed-9c5b-3d2fc34565f1)

**Comment by Twiyin0** [comment]
重启插件即可
